#!/bin/bash

# Parameters
## A number indicating which version number has to change. The posible values are 1, 2, or 3 indicating major, minor and revision respectively.
## A version number with format a.b.c . a, b and c have a format of \d+.
# Returns
## A version with the number version indicated augmented
basic_augmentation(){
  echo $1 | awk -F '.' "{\$$2=\$$2+1 ; print \$1\".\"\$2\".\"\$3}"
}

# Parameters
## A version number with format a.b.c . a, b and c have a format of \d+.
# Returns
## A version with number a+1.b.c
major_augmentation(){
  basic_augmentation $1 1
}

# Parameters
## A version number with format a.b.c . a, b and c have a format of \d+.
# Returns
## A version with number a.b+1.c
minor_augmentation(){
  basic_augmentation $1 2
}

# Parameters
## A version number with format a.b.c . a, b and c have a format of \d+.
# Returns
## A version with number a.b.c+1
revision_augmentation(){
  basic_augmentation $1 3
}
